### ISSUE TITLE
DSDT.aml for bios 302 have problems

### ISSUE THREAD

**Issue by Jeffernic** [nguyentrucxinh/ASUS-VivoBook-X510UQR-Hackintosh#1]
if i use DSDT.aml , clover will restart timellief

**Comment by nguyentrucxinh** [comment]
Hi @Jeffernic 

Here is my current CLOVER folder in EFI.
Let's try
[CLOVER_10-Nov-2018.zip](https://github.com/nguyentrucxinh/ASUS-VivoBook-X510UQR-Hackintosh/files/2568363/CLOVER_10-Nov-2018.zip)

Good luck!

**Comment by Jeffernic** [comment]
There 's happen again.
I guess its from my different cpu or my internet card,because my cpu is i5 8250 
maybe just from my bios software

**Comment by Jeffernic** [comment]
[CLOVER v4741 .zip](https://github.com/nguyentrucxinh/ASUS-VivoBook-X510UQR-Hackintosh/files/2568427/CLOVER.v4741.zip)
This my clover ,its work with the newest clover

**Comment by nguyentrucxinh** [comment]
Did you resolve the issue after update to newest Clover?
Now your Hackintosh working perfect, right?

**Comment by Jeffernic** [comment]
This issue still have at newest clover

**Comment by nglequduph** [comment]
I have the same issue, system cannot load after copy this file DSDT.aml

**Comment by nguyentrucxinh** [comment]
@Jeffernic @nglequduph 
Let's try using the newest EFI in here https://github.com/nguyentrucxinh/ASUS-VivoBook-X510UQR-Hackintosh/tree/master/EFI_AFTER/MacOS_Version_10-14-1_v2 (also work for 10.14.2)
Do not copy DSDT.aml & SSDT.aml patched to the EFI, because it existed hot patch by Clover for it.

More info:
The DSDT.aml & SSDT.aml just work when you have the same machine with me. But hot patch by Clover will work for more machine.

**Comment by nguyentrucxinh** [comment]
@nglequduph 
This is a common issue when we use multiple OS in the same machine.
Here is the solution for this:
https://www.tonymacx86.com/threads/fix-incorrect-time-in-windows-osx-dual-boot.133719/

Good luck!

**Comment by Jeffernic** [comment]
I have solved the problem.
We just need to reinstall the system

**Comment by nguyentrucxinh** [comment]
@Jeffernic 
Glad to hear from you
Happy funny with your machine!
